# Generated by Django 3.2.5 on 2022-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion de la empresa')),
                ('nombreEmpresa', models.CharField(max_length=200, verbose_name='nombre de la empresa')),
                ('telefonoEmpresa', models.BigIntegerField(verbose_name='telefono de la empresa')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT de la empresa')),
            ],
        ),
    ]
